sudo: false
os:
- linux
- osx

osx_image: xcode8.3
dist: trusty

language: node_js
node_js:
- '4'
- '6'
- '8'
cache:
  directories:
  - node_modules

before_install:
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
  - master
